"""
Seed Script – 100+ policies across 8 providers for meaningful recommendation variety.
"""

from app.database import SessionLocal, engine, Base
from app.models import Provider, Policy

Base.metadata.create_all(bind=engine)


def seed():
    db = SessionLocal()
    try:
        if db.query(Provider).count() > 0:
            print("⚠️  Database already has providers – skipping seed.")
            return

        # ━━━━━━━━━━ PROVIDERS ━━━━━━━━━━
        providers = [
            Provider(name="LIC of India", country="India"),
            Provider(name="HDFC Ergo", country="India"),
            Provider(name="ICICI Lombard", country="India"),
            Provider(name="Star Health", country="India"),
            Provider(name="Bajaj Allianz", country="India"),
            Provider(name="Max Life", country="India"),
            Provider(name="Tata AIG", country="India"),
            Provider(name="SBI General", country="India"),
        ]
        db.add_all(providers)
        db.flush()

        lic, hdfc, icici, star, bajaj, maxlife, tata, sbi = providers

        policies = []

        # ═══════════════════════════════════════════
        #  LIFE INSURANCE — 22 policies
        # ═══════════════════════════════════════════

        policies += [
            Policy(provider_id=lic.id, policy_type="life", title="LIC Jeevan Anand",
                   coverage={"death_benefit": "10,00,000", "maturity_benefit": "10,00,000", "bonus": "yearly", "loan_facility": True},
                   premium=5000, term_months=240, deductible=0, tnc_url="#"),
            Policy(provider_id=lic.id, policy_type="life", title="LIC Tech Term",
                   coverage={"death_benefit": "1,00,00,000", "maturity_benefit": "None (pure term)", "accidental_death_rider": True, "online_purchase": True},
                   premium=1200, term_months=360, deductible=0, tnc_url="#"),
            Policy(provider_id=lic.id, policy_type="life", title="LIC Bima Jyoti",
                   coverage={"death_benefit": "5,00,000", "maturity_benefit": "guaranteed", "limited_pay": True},
                   premium=3200, term_months=180, deductible=0, tnc_url="#"),
            Policy(provider_id=lic.id, policy_type="life", title="LIC Saral Jeevan Bima",
                   coverage={"death_benefit": "25,00,000", "maturity_benefit": "None (pure term)", "simple_plan": True},
                   premium=900, term_months=240, deductible=0, tnc_url="#"),
            Policy(provider_id=hdfc.id, policy_type="life", title="HDFC Life Click 2 Protect",
                   coverage={"death_benefit": "50,00,000", "terminal_illness": True, "waiver_of_premium": True, "return_of_premium": "optional"},
                   premium=2500, term_months=300, deductible=0, tnc_url="#"),
            Policy(provider_id=hdfc.id, policy_type="life", title="HDFC Life Sanchay Plus",
                   coverage={"death_benefit": "15,00,000", "guaranteed_income": True, "maturity_benefit": "guaranteed", "loan_facility": True},
                   premium=8000, term_months=180, deductible=0, tnc_url="#"),
            Policy(provider_id=hdfc.id, policy_type="life", title="HDFC Life ProGrowth Super II",
                   coverage={"death_benefit": "10,00,000", "ULIP": True, "wealth_creation": True, "partial_withdrawal": True},
                   premium=5500, term_months=240, deductible=0, tnc_url="#"),
            Policy(provider_id=bajaj.id, policy_type="life", title="Bajaj Smart Protect Goal",
                   coverage={"death_benefit": "25,00,000", "critical_illness_rider": True, "accidental_disability": True, "flexible_payout": "lump sum or monthly"},
                   premium=1800, term_months=240, deductible=0, tnc_url="#"),
            Policy(provider_id=bajaj.id, policy_type="life", title="Bajaj iSecure Term Plan",
                   coverage={"death_benefit": "75,00,000", "terminal_illness": True, "return_of_premium": True},
                   premium=2200, term_months=300, deductible=0, tnc_url="#"),
            Policy(provider_id=maxlife.id, policy_type="life", title="Max Life Smart Secure Plus",
                   coverage={"death_benefit": "75,00,000", "terminal_illness": True, "waiver_of_premium": True, "family_income_benefit": "monthly payout"},
                   premium=3500, term_months=360, deductible=0, tnc_url="#"),
            Policy(provider_id=maxlife.id, policy_type="life", title="Max Life Child – Future Genius",
                   coverage={"death_benefit": "20,00,000", "child_education_fund": True, "waiver_of_premium_on_parent_death": True, "guaranteed_additions": "yearly", "family_plan": True},
                   premium=3000, term_months=180, deductible=0, tnc_url="#"),
            Policy(provider_id=maxlife.id, policy_type="life", title="Max Life Whole Life Super",
                   coverage={"death_benefit": "50,00,000", "whole_life": True, "bonus": "yearly", "loan_facility": True},
                   premium=6500, term_months=600, deductible=0, tnc_url="#"),
            Policy(provider_id=tata.id, policy_type="life", title="Tata AIG Senior Shield",
                   coverage={"death_benefit": "15,00,000", "critical_illness": True, "age_limit": "up to 70", "no_medical_test": "up to 5L"},
                   premium=4500, term_months=60, deductible=0, tnc_url="#"),
            Policy(provider_id=tata.id, policy_type="life", title="Tata AIG Life – iProtect Plus",
                   coverage={"death_benefit": "2,00,00,000", "terminal_illness": True, "accidental_death": "2x", "36_critical_illnesses": True},
                   premium=2800, term_months=360, deductible=0, tnc_url="#"),
            Policy(provider_id=icici.id, policy_type="life", title="ICICI Pru iProtect Smart",
                   coverage={"death_benefit": "1,00,00,000", "accidental_death": "2x", "terminal_illness_lump_sum": True, "30_critical_illnesses": True},
                   premium=1500, term_months=300, deductible=0, tnc_url="#"),
            Policy(provider_id=icici.id, policy_type="life", title="ICICI Pru Guaranteed Income",
                   coverage={"death_benefit": "12,00,000", "guaranteed_income": True, "maturity_benefit": "lump sum", "tax_benefits": True},
                   premium=4200, term_months=180, deductible=0, tnc_url="#"),
            Policy(provider_id=sbi.id, policy_type="life", title="SBI Life eShield Next",
                   coverage={"death_benefit": "50,00,000", "terminal_illness": True, "accidental_death": True, "waiver_of_premium": True},
                   premium=1650, term_months=300, deductible=0, tnc_url="#"),
            Policy(provider_id=sbi.id, policy_type="life", title="SBI Life Saral Pension",
                   coverage={"death_benefit": "10,00,000", "pension_plan": True, "guaranteed_additions": True, "annuity_options": True},
                   premium=7000, term_months=240, deductible=0, tnc_url="#"),
            Policy(provider_id=sbi.id, policy_type="life", title="SBI Life – Retire Smart",
                   coverage={"death_benefit": "20,00,000", "retirement_plan": True, "partial_withdrawal": True, "guaranteed_maturity": True},
                   premium=6000, term_months=120, deductible=0, tnc_url="#"),
            Policy(provider_id=lic.id, policy_type="life", title="LIC Jeevan Umang",
                   coverage={"death_benefit": "12,00,000", "whole_life": True, "survival_benefit": "8% of sum assured per year", "maturity_benefit": True},
                   premium=4800, term_months=600, deductible=0, tnc_url="#"),
            Policy(provider_id=bajaj.id, policy_type="life", title="Bajaj Life – Rising Star Child",
                   coverage={"death_benefit": "15,00,000", "child_education_fund": True, "family_plan": True, "waiver_on_parent_death": True, "guaranteed_additions": True},
                   premium=3800, term_months=180, deductible=0, tnc_url="#"),
            Policy(provider_id=tata.id, policy_type="life", title="Tata AIG – 5 Year Quick Term",
                   coverage={"death_benefit": "10,00,000", "short_term": True, "quick_issuance": True, "no_medical_test": "up to 10L"},
                   premium=1100, term_months=60, deductible=0, tnc_url="#"),
        ]

        # ═══════════════════════════════════════════
        #  HEALTH INSURANCE — 22 policies
        # ═══════════════════════════════════════════

        policies += [
            Policy(provider_id=hdfc.id, policy_type="health", title="HDFC Ergo Optima Secure",
                   coverage={"sum_insured": "5,00,000", "room_rent": "no_cap", "pre_hospitalization": "30_days", "post_hospitalization": "60_days", "daycare_procedures": True},
                   premium=8500, term_months=12, deductible=5000, tnc_url="#"),
            Policy(provider_id=hdfc.id, policy_type="health", title="HDFC Ergo My Health Suraksha",
                   coverage={"sum_insured": "10,00,000", "room_rent": "no_cap", "restoration": "100%", "ayush": True, "organ_donor": True},
                   premium=14000, term_months=12, deductible=3000, tnc_url="#"),
            Policy(provider_id=lic.id, policy_type="health", title="LIC Cancer Cover",
                   coverage={"sum_insured": "10,00,000", "early_stage": "25%", "major_stage": "100%", "income_benefit": "1% monthly for 5 years"},
                   premium=2000, term_months=12, deductible=0, tnc_url="#"),
            Policy(provider_id=lic.id, policy_type="health", title="LIC Arogya Rakshak",
                   coverage={"sum_insured": "7,00,000", "room_rent": "2% of SI", "pre_hospitalization": "30_days", "ambulance": "2,000"},
                   premium=5500, term_months=12, deductible=2000, tnc_url="#"),
            Policy(provider_id=star.id, policy_type="health", title="Star Health Comprehensive",
                   coverage={"sum_insured": "10,00,000", "room_rent": "single_ac_room", "maternity_benefit": True, "new_born_cover": True, "organ_donor": True, "ayush_treatment": True, "family_plan": True},
                   premium=12000, term_months=12, deductible=3000, tnc_url="#"),
            Policy(provider_id=star.id, policy_type="health", title="Star Family Health Optima",
                   coverage={"sum_insured": "15,00,000", "family_floater": True, "maternity_benefit": True, "new_born_cover": True, "child_vaccination": True, "room_rent": "no_cap", "restoration_benefit": "100%", "family_plan": True},
                   premium=18000, term_months=12, deductible=5000, tnc_url="#"),
            Policy(provider_id=star.id, policy_type="health", title="Star Young Star",
                   coverage={"sum_insured": "3,00,000", "room_rent": "1% SI", "pre_hospitalization": "30_days", "post_hospitalization": "60_days", "fitness_discount": "10%"},
                   premium=3200, term_months=12, deductible=1000, tnc_url="#"),
            Policy(provider_id=bajaj.id, policy_type="health", title="Bajaj Health Guard",
                   coverage={"sum_insured": "3,00,000", "room_rent": "1% of sum insured", "pre_hospitalization": "60_days", "post_hospitalization": "90_days", "ambulance_cover": "2,000"},
                   premium=5500, term_months=12, deductible=2000, tnc_url="#"),
            Policy(provider_id=bajaj.id, policy_type="health", title="Bajaj Health Guard Gold",
                   coverage={"sum_insured": "10,00,000", "room_rent": "no_cap", "maternity": True, "vaccination": True, "no_claim_bonus": "50%", "family_plan": True},
                   premium=16500, term_months=12, deductible=3000, tnc_url="#"),
            Policy(provider_id=tata.id, policy_type="health", title="Tata AIG MediCare Plus",
                   coverage={"sum_insured": "8,00,000", "room_rent": "1% of SI", "pre_hospitalization": "30_days", "post_hospitalization": "60_days", "ayush_treatment": True, "domiciliary_treatment": True},
                   premium=6500, term_months=12, deductible=2500, tnc_url="#"),
            Policy(provider_id=tata.id, policy_type="health", title="Tata AIG MediCare Premier",
                   coverage={"sum_insured": "25,00,000", "room_rent": "no_cap", "worldwide_emergency": True, "organ_donor": True, "restoration": "unlimited", "family_plan": True},
                   premium=28000, term_months=12, deductible=5000, tnc_url="#"),
            Policy(provider_id=maxlife.id, policy_type="health", title="Max Bupa Health Recharge",
                   coverage={"sum_insured": "20,00,000", "room_rent": "no_cap", "recharge_benefit": "100% restoration", "pre_existing_cover_after": "2 years", "no_claim_bonus": "10% per year", "organ_donor": True},
                   premium=15000, term_months=12, deductible=0, tnc_url="#"),
            Policy(provider_id=maxlife.id, policy_type="health", title="Max Bupa GoActive",
                   coverage={"sum_insured": "5,00,000", "room_rent": "single_AC", "fitness_rewards": True, "health_checkup": True, "mental_health_cover": True},
                   premium=4800, term_months=12, deductible=1500, tnc_url="#"),
            Policy(provider_id=icici.id, policy_type="health", title="ICICI Lombard Senior Citizen Health",
                   coverage={"sum_insured": "5,00,000", "min_entry_age": 60, "room_rent": "single_ac", "pre_existing_cover_after": "1 year", "domiciliary_treatment": True, "cataract_cover": "40,000"},
                   premium=22000, term_months=12, deductible=10000, tnc_url="#"),
            Policy(provider_id=icici.id, policy_type="health", title="ICICI Lombard Health Booster",
                   coverage={"sum_insured": "50,00,000", "super_top_up": True, "room_rent": "no_cap", "worldwide_emergency": True},
                   premium=3500, term_months=12, deductible=15000, tnc_url="#"),
            Policy(provider_id=sbi.id, policy_type="health", title="SBI General Arogya Supreme",
                   coverage={"sum_insured": "5,00,000", "room_rent": "1% SI", "pre_hospitalization": "60_days", "alternative_treatment": True},
                   premium=4500, term_months=12, deductible=2000, tnc_url="#"),
            Policy(provider_id=sbi.id, policy_type="health", title="SBI Health – Family First",
                   coverage={"sum_insured": "12,00,000", "family_floater": True, "maternity": True, "new_born_cover": True, "child_vaccination": True, "family_plan": True},
                   premium=16000, term_months=12, deductible=4000, tnc_url="#"),
            Policy(provider_id=sbi.id, policy_type="health", title="SBI Health – Diabetes Care",
                   coverage={"sum_insured": "5,00,000", "diabetes_cover": True, "pre_existing_cover": True, "regular_checkups": True},
                   premium=9000, term_months=12, deductible=5000, tnc_url="#"),
            Policy(provider_id=star.id, policy_type="health", title="Star Super Surplus",
                   coverage={"sum_insured": "25,00,000", "super_top_up": True, "room_rent": "no_cap", "no_sublimits": True},
                   premium=5000, term_months=12, deductible=10000, tnc_url="#"),
            Policy(provider_id=bajaj.id, policy_type="health", title="Bajaj Global Health Secure",
                   coverage={"sum_insured": "50,00,000", "worldwide_treatment": True, "room_rent": "no_cap", "second_opinion": True, "air_ambulance": True},
                   premium=35000, term_months=12, deductible=8000, tnc_url="#"),
            Policy(provider_id=lic.id, policy_type="health", title="LIC Jeevan Arogya – Senior",
                   coverage={"sum_insured": "3,00,000", "room_rent": "3,000/day", "pre_existing_after": "2 years", "ambulance": "2,000", "senior_friendly": True},
                   premium=11000, term_months=12, deductible=3000, tnc_url="#"),
            Policy(provider_id=icici.id, policy_type="health", title="ICICI Complete Health",
                   coverage={"sum_insured": "5,00,000", "room_rent": "no_cap", "pre_hospitalization": "60_days", "post_hospitalization": "180_days", "maternity": True, "family_plan": True},
                   premium=9500, term_months=12, deductible=2000, tnc_url="#"),
        ]

        # ═══════════════════════════════════════════
        #  AUTO INSURANCE — 20 policies
        # ═══════════════════════════════════════════

        policies += [
            Policy(provider_id=icici.id, policy_type="auto", title="ICICI Lombard Car Insurance",
                   coverage={"own_damage": "IDV based", "third_party": "unlimited", "personal_accident": "15,00,000", "roadside_assistance": True},
                   premium=12000, term_months=12, deductible=2500, tnc_url="#"),
            Policy(provider_id=icici.id, policy_type="auto", title="ICICI Budget Car Plan",
                   coverage={"own_damage": "IDV based", "third_party": "unlimited", "personal_accident": "5,00,000"},
                   premium=5500, term_months=12, deductible=3000, tnc_url="#"),
            Policy(provider_id=icici.id, policy_type="auto", title="ICICI Two Wheeler Shield",
                   coverage={"own_damage": "IDV based", "third_party": "unlimited", "personal_accident": "1,00,000", "pillion_cover": True},
                   premium=2800, term_months=12, deductible=500, tnc_url="#"),
            Policy(provider_id=hdfc.id, policy_type="auto", title="HDFC Ergo Motor Insurance",
                   coverage={"own_damage": "IDV based", "third_party": "unlimited", "zero_depreciation": True, "engine_protection": True, "key_replacement": True},
                   premium=15000, term_months=12, deductible=1000, tnc_url="#"),
            Policy(provider_id=hdfc.id, policy_type="auto", title="HDFC Ergo – Third Party Only",
                   coverage={"third_party": "unlimited", "personal_accident": "15,00,000"},
                   premium=6000, term_months=12, deductible=0, tnc_url="#"),
            Policy(provider_id=bajaj.id, policy_type="auto", title="Bajaj Two Wheeler Insurance",
                   coverage={"own_damage": "IDV based", "third_party": "unlimited", "personal_accident": "1,00,000", "roadside_assistance": True},
                   premium=3500, term_months=12, deductible=500, tnc_url="#"),
            Policy(provider_id=bajaj.id, policy_type="auto", title="Bajaj Allianz EV Auto Cover",
                   coverage={"own_damage": "IDV based", "third_party": "unlimited", "battery_protection": True, "charging_equipment_cover": True, "roadside_assistance": True},
                   premium=8000, term_months=36, deductible=2000, tnc_url="#"),
            Policy(provider_id=bajaj.id, policy_type="auto", title="Bajaj Allianz Premium Car Plan",
                   coverage={"own_damage": "IDV based", "third_party": "unlimited", "zero_depreciation": True, "engine_protection": True, "NCB_protect": True, "return_to_invoice": True, "consumable_cover": True},
                   premium=22000, term_months=12, deductible=1000, tnc_url="#"),
            Policy(provider_id=star.id, policy_type="auto", title="Star Commercial Vehicle Cover",
                   coverage={"own_damage": "IDV based", "third_party": "unlimited", "goods_in_transit": "5,00,000", "driver_cover": "2,00,000"},
                   premium=22000, term_months=12, deductible=5000, tnc_url="#"),
            Policy(provider_id=tata.id, policy_type="auto", title="Tata AIG Auto Secure",
                   coverage={"own_damage": "IDV based", "third_party": "unlimited", "zero_depreciation": True, "consumable_cover": True, "NCB_protect": True, "return_to_invoice": True},
                   premium=9000, term_months=12, deductible=1500, tnc_url="#"),
            Policy(provider_id=tata.id, policy_type="auto", title="Tata AIG Two Wheeler Plus",
                   coverage={"own_damage": "IDV based", "third_party": "unlimited", "personal_accident": "2,00,000", "roadside_assistance": True, "zero_depreciation": True},
                   premium=4200, term_months=12, deductible=500, tnc_url="#"),
            Policy(provider_id=maxlife.id, policy_type="auto", title="Max Auto – 3 Year Plan",
                   coverage={"own_damage": "IDV based", "third_party": "unlimited", "zero_depreciation": True, "NCB_protect": True, "long_term_discount": "15%"},
                   premium=11000, term_months=36, deductible=1500, tnc_url="#"),
            Policy(provider_id=sbi.id, policy_type="auto", title="SBI General Motor Insurance",
                   coverage={"own_damage": "IDV based", "third_party": "unlimited", "personal_accident": "15,00,000", "zero_depreciation": True, "engine_protection": True},
                   premium=13500, term_months=12, deductible=2000, tnc_url="#"),
            Policy(provider_id=sbi.id, policy_type="auto", title="SBI General Two Wheeler",
                   coverage={"own_damage": "IDV based", "third_party": "unlimited", "personal_accident": "1,00,000"},
                   premium=2500, term_months=12, deductible=400, tnc_url="#"),
            Policy(provider_id=sbi.id, policy_type="auto", title="SBI Auto – Comprehensive Plus",
                   coverage={"own_damage": "IDV based", "third_party": "unlimited", "zero_depreciation": True, "engine_protection": True, "NCB_protect": True, "roadside_assistance": True, "consumable_cover": True},
                   premium=18000, term_months=12, deductible=1000, tnc_url="#"),
            Policy(provider_id=lic.id, policy_type="auto", title="LIC Motor – Basic Third Party",
                   coverage={"third_party": "unlimited", "personal_accident": "15,00,000"},
                   premium=4500, term_months=12, deductible=0, tnc_url="#"),
            Policy(provider_id=hdfc.id, policy_type="auto", title="HDFC Ergo Car Protect Premium",
                   coverage={"own_damage": "IDV based", "third_party": "unlimited", "zero_depreciation": True, "engine_protection": True, "NCB_protect": True, "tyre_cover": True, "personal_belongings_cover": True},
                   premium=25000, term_months=12, deductible=500, tnc_url="#"),
            Policy(provider_id=tata.id, policy_type="auto", title="Tata AIG – Electric Vehicle Ultra",
                   coverage={"own_damage": "IDV based", "third_party": "unlimited", "battery_protection": True, "wall_charger_cover": True, "zero_depreciation": True, "roadside_assistance": True},
                   premium=10500, term_months=36, deductible=1500, tnc_url="#"),
            Policy(provider_id=bajaj.id, policy_type="auto", title="Bajaj Bike Protect Basic",
                   coverage={"own_damage": "IDV based", "third_party": "unlimited"},
                   premium=1800, term_months=12, deductible=300, tnc_url="#"),
            Policy(provider_id=icici.id, policy_type="auto", title="ICICI Lombard – 5 Year Car Plan",
                   coverage={"own_damage": "IDV based", "third_party": "unlimited", "zero_depreciation": True, "long_term_discount": "20%", "NCB_protect": True},
                   premium=14000, term_months=60, deductible=2000, tnc_url="#"),
        ]

        # ═══════════════════════════════════════════
        #  HOME INSURANCE — 20 policies
        # ═══════════════════════════════════════════

        policies += [
            Policy(provider_id=hdfc.id, policy_type="home", title="HDFC Ergo Home Shield",
                   coverage={"structure": "50,00,000", "contents": "10,00,000", "natural_disaster": True, "theft": True},
                   premium=3500, term_months=12, deductible=1000, tnc_url="#"),
            Policy(provider_id=hdfc.id, policy_type="home", title="HDFC Ergo Home Shield Gold",
                   coverage={"structure": "1,00,00,000", "contents": "25,00,000", "earthquake": True, "terrorism": True, "rent_loss": "60,000", "family_plan": True},
                   premium=7500, term_months=12, deductible=2000, tnc_url="#"),
            Policy(provider_id=bajaj.id, policy_type="home", title="Bajaj Allianz Home Insurance",
                   coverage={"structure": "30,00,000", "contents": "5,00,000", "fire_damage": True, "flood_damage": True, "burglary": True},
                   premium=2800, term_months=12, deductible=500, tnc_url="#"),
            Policy(provider_id=bajaj.id, policy_type="home", title="Bajaj Home – Tenant Shield",
                   coverage={"contents": "8,00,000", "theft": True, "fire_damage": True, "electronic_equipment": "1,50,000", "landlord_liability": True},
                   premium=1500, term_months=12, deductible=300, tnc_url="#"),
            Policy(provider_id=icici.id, policy_type="home", title="ICICI Lombard Home Protect",
                   coverage={"structure": "1,00,00,000", "contents": "20,00,000", "earthquake": True, "terrorism": True, "rent_for_alternate_accommodation": "50,000"},
                   premium=6000, term_months=12, deductible=2000, tnc_url="#"),
            Policy(provider_id=icici.id, policy_type="home", title="ICICI Home – 5 Year Lock-In",
                   coverage={"structure": "80,00,000", "contents": "15,00,000", "earthquake": True, "terrorism": True, "long_term_discount": "20%"},
                   premium=4200, term_months=60, deductible=2000, tnc_url="#"),
            Policy(provider_id=star.id, policy_type="home", title="Star Home Secure Plus",
                   coverage={"structure": "75,00,000", "contents": "15,00,000", "jewellery": "2,00,000", "electronic_equipment": "3,00,000", "public_liability": True},
                   premium=4500, term_months=12, deductible=1500, tnc_url="#"),
            Policy(provider_id=tata.id, policy_type="home", title="Tata AIG Home Protect Premium",
                   coverage={"structure": "1,50,00,000", "contents": "30,00,000", "earthquake": True, "flood": True, "terrorism": True, "rent_loss": "1,00,000", "family_liability": True, "family_plan": True},
                   premium=9500, term_months=12, deductible=3000, tnc_url="#"),
            Policy(provider_id=tata.id, policy_type="home", title="Tata AIG Home – Basic Fire",
                   coverage={"structure": "20,00,000", "fire_damage": True, "lightning": True, "explosion": True},
                   premium=1200, term_months=12, deductible=500, tnc_url="#"),
            Policy(provider_id=maxlife.id, policy_type="home", title="Max Home Essential",
                   coverage={"structure": "20,00,000", "contents": "3,00,000", "fire_damage": True, "lightning": True, "explosion": True},
                   premium=1800, term_months=12, deductible=500, tnc_url="#"),
            Policy(provider_id=sbi.id, policy_type="home", title="SBI General Home Insurance",
                   coverage={"structure": "50,00,000", "contents": "10,00,000", "fire": True, "burglary": True, "earthquake": True, "flood": True},
                   premium=3800, term_months=12, deductible=1000, tnc_url="#"),
            Policy(provider_id=sbi.id, policy_type="home", title="SBI General Home Premium Plus",
                   coverage={"structure": "2,00,00,000", "contents": "40,00,000", "earthquake": True, "terrorism": True, "jewellery": "5,00,000", "electronic_equipment": "5,00,000", "family_plan": True},
                   premium=12000, term_months=12, deductible=5000, tnc_url="#"),
            Policy(provider_id=sbi.id, policy_type="home", title="SBI Renter's Contents Cover",
                   coverage={"contents": "5,00,000", "theft": True, "fire": True, "electronic_equipment": "1,00,000"},
                   premium=1000, term_months=12, deductible=200, tnc_url="#"),
            Policy(provider_id=bajaj.id, policy_type="home", title="Bajaj Home – Earthquake Add-On",
                   coverage={"structure": "40,00,000", "contents": "8,00,000", "earthquake": True, "fire": True, "flood": True},
                   premium=3200, term_months=12, deductible=1500, tnc_url="#"),
            Policy(provider_id=icici.id, policy_type="home", title="ICICI Home Secure Basic",
                   coverage={"structure": "25,00,000", "fire": True, "lightning": True, "explosion": True},
                   premium=1500, term_months=12, deductible=500, tnc_url="#"),
            Policy(provider_id=lic.id, policy_type="home", title="LIC Griha Suraksha – Home",
                   coverage={"structure": "60,00,000", "contents": "12,00,000", "fire": True, "burglary": True, "flood": True, "earthquake": True},
                   premium=4200, term_months=12, deductible=1000, tnc_url="#"),
            Policy(provider_id=lic.id, policy_type="home", title="LIC Griha Suraksha Premium",
                   coverage={"structure": "1,50,00,000", "contents": "30,00,000", "earthquake": True, "terrorism": True, "family_liability": True, "family_plan": True},
                   premium=8500, term_months=12, deductible=3000, tnc_url="#"),
            Policy(provider_id=maxlife.id, policy_type="home", title="Max Home – Smart Home Cover",
                   coverage={"structure": "40,00,000", "contents": "10,00,000", "smart_devices": "2,00,000", "cyber_fraud": "50,000", "fire": True, "theft": True},
                   premium=4000, term_months=12, deductible=1000, tnc_url="#"),
            Policy(provider_id=tata.id, policy_type="home", title="Tata AIG Home – Long Term (3yr)",
                   coverage={"structure": "75,00,000", "contents": "15,00,000", "earthquake": True, "terrorism": True, "long_term_discount": "15%"},
                   premium=3800, term_months=36, deductible=1500, tnc_url="#"),
            Policy(provider_id=hdfc.id, policy_type="home", title="HDFC Ergo – Landlord Protect",
                   coverage={"structure": "80,00,000", "rent_loss": "1,20,000", "tenant_damages": "3,00,000", "legal_liability": True},
                   premium=5200, term_months=12, deductible=2000, tnc_url="#"),
        ]

        # ═══════════════════════════════════════════
        #  TRAVEL INSURANCE — 20 policies
        # ═══════════════════════════════════════════

        policies += [
            Policy(provider_id=icici.id, policy_type="travel", title="ICICI Lombard Travel Safe",
                   coverage={"medical_emergency": "5,00,000", "trip_cancellation": "1,00,000", "baggage_loss": "50,000", "flight_delay": "10,000"},
                   premium=1500, term_months=1, deductible=500, tnc_url="#"),
            Policy(provider_id=icici.id, policy_type="travel", title="ICICI Lombard Student Travel",
                   coverage={"medical_emergency": "30,00,000", "study_interruption": "2,00,000", "sponsor_visit": "50,000", "baggage_loss": "1,00,000", "student_plan": True},
                   premium=5000, term_months=12, deductible=1500, tnc_url="#"),
            Policy(provider_id=bajaj.id, policy_type="travel", title="Bajaj Allianz Travel Elite",
                   coverage={"medical_emergency": "15,00,000", "trip_cancellation": "3,00,000", "baggage_loss": "1,00,000", "passport_loss": "25,000", "hijack_distress": "10,000"},
                   premium=3500, term_months=1, deductible=1000, tnc_url="#"),
            Policy(provider_id=bajaj.id, policy_type="travel", title="Bajaj Budget Backpacker",
                   coverage={"medical_emergency": "3,00,000", "trip_cancellation": "50,000", "baggage_loss": "25,000"},
                   premium=800, term_months=1, deductible=300, tnc_url="#"),
            Policy(provider_id=bajaj.id, policy_type="travel", title="Bajaj Domestic Travel Cover",
                   coverage={"medical_emergency": "2,00,000", "trip_cancellation": "30,000", "baggage_loss": "15,000", "domestic_only": True},
                   premium=500, term_months=1, deductible=200, tnc_url="#"),
            Policy(provider_id=hdfc.id, policy_type="travel", title="HDFC Ergo Travel Wallet",
                   coverage={"medical_emergency": "7,50,000", "trip_cancellation": "2,00,000", "baggage_delay": "15,000", "missed_connection": "20,000", "adventure_sports": True},
                   premium=2200, term_months=1, deductible=750, tnc_url="#"),
            Policy(provider_id=hdfc.id, policy_type="travel", title="HDFC Ergo – Corporate Travel",
                   coverage={"medical_emergency": "10,00,000", "trip_cancellation": "3,00,000", "laptop_cover": "50,000", "flight_delay": "15,000", "business_trip": True},
                   premium=3800, term_months=1, deductible=1000, tnc_url="#"),
            Policy(provider_id=star.id, policy_type="travel", title="Star Travel Protect Gold",
                   coverage={"medical_emergency": "10,00,000", "trip_cancellation": "2,50,000", "baggage_loss": "75,000", "home_burglary_during_travel": "1,00,000", "emergency_evacuation": True},
                   premium=2800, term_months=1, deductible=500, tnc_url="#"),
            Policy(provider_id=star.id, policy_type="travel", title="Star Senior Citizen Travel",
                   coverage={"medical_emergency": "15,00,000", "pre_existing_cover": True, "trip_cancellation": "2,00,000", "emergency_evacuation": True, "senior_friendly": True},
                   premium=6500, term_months=1, deductible=2000, tnc_url="#"),
            Policy(provider_id=tata.id, policy_type="travel", title="Tata AIG Travel Guard – Annual",
                   coverage={"medical_emergency": "25,00,000", "trip_cancellation": "5,00,000", "baggage_loss": "1,50,000", "annual_multi_trip": True, "adventure_sports": True, "home_burglary": True},
                   premium=8500, term_months=12, deductible=2000, tnc_url="#"),
            Policy(provider_id=tata.id, policy_type="travel", title="Tata AIG – Asia Travel Basic",
                   coverage={"medical_emergency": "5,00,000", "trip_cancellation": "1,00,000", "baggage_loss": "30,000", "asia_coverage": True},
                   premium=1200, term_months=1, deductible=400, tnc_url="#"),
            Policy(provider_id=maxlife.id, policy_type="travel", title="Max Travel – Family Pack",
                   coverage={"medical_emergency": "12,00,000", "trip_cancellation": "3,00,000", "family_floater": True, "child_cover": True, "baggage_loss": "1,00,000", "family_plan": True},
                   premium=4500, term_months=1, deductible=1000, tnc_url="#"),
            Policy(provider_id=maxlife.id, policy_type="travel", title="Max Travel Premium Worldwide",
                   coverage={"medical_emergency": "50,00,000", "trip_cancellation": "10,00,000", "baggage_loss": "2,00,000", "adventure_sports": True, "worldwide_cover": True, "concierge_service": True},
                   premium=12000, term_months=1, deductible=3000, tnc_url="#"),
            Policy(provider_id=sbi.id, policy_type="travel", title="SBI General Travel Protect",
                   coverage={"medical_emergency": "8,00,000", "trip_cancellation": "2,00,000", "baggage_loss": "60,000", "flight_delay": "10,000"},
                   premium=2000, term_months=1, deductible=500, tnc_url="#"),
            Policy(provider_id=sbi.id, policy_type="travel", title="SBI General – Annual Multi-Trip",
                   coverage={"medical_emergency": "20,00,000", "trip_cancellation": "4,00,000", "baggage_loss": "1,00,000", "annual_multi_trip": True, "business_trip": True},
                   premium=7000, term_months=12, deductible=1500, tnc_url="#"),
            Policy(provider_id=sbi.id, policy_type="travel", title="SBI General – Schengen Visa",
                   coverage={"medical_emergency": "30,00,000", "trip_cancellation": "3,00,000", "schengen_compliant": True, "emergency_evacuation": True, "baggage_loss": "1,00,000"},
                   premium=3500, term_months=1, deductible=1000, tnc_url="#"),
            Policy(provider_id=lic.id, policy_type="travel", title="LIC Travel Smart",
                   coverage={"medical_emergency": "5,00,000", "trip_cancellation": "1,00,000", "baggage_loss": "50,000"},
                   premium=1500, term_months=1, deductible=500, tnc_url="#"),
            Policy(provider_id=lic.id, policy_type="travel", title="LIC Travel Smart Plus",
                   coverage={"medical_emergency": "15,00,000", "trip_cancellation": "3,00,000", "baggage_loss": "1,00,000", "adventure_sports": True, "emergency_evacuation": True},
                   premium=4000, term_months=1, deductible=1000, tnc_url="#"),
            Policy(provider_id=icici.id, policy_type="travel", title="ICICI Lombard World Traveller",
                   coverage={"medical_emergency": "40,00,000", "trip_cancellation": "8,00,000", "baggage_loss": "2,00,000", "worldwide_cover": True, "adventure_sports": True, "concierge_service": True},
                   premium=9500, term_months=1, deductible=2500, tnc_url="#"),
            Policy(provider_id=tata.id, policy_type="travel", title="Tata AIG – Honeymoon Travel",
                   coverage={"medical_emergency": "10,00,000", "trip_cancellation": "2,00,000", "baggage_loss": "75,000", "honeymoon_benefit": "25,000", "couple_plan": True},
                   premium=3200, term_months=1, deductible=800, tnc_url="#"),
        ]

        db.add_all(policies)
        db.commit()
        print(f"✅  Seeded {len(providers)} providers and {len(policies)} policies.")
    finally:
        db.close()


if __name__ == "__main__":
    seed()
